### ISSUE TITLE
Only first line gets Segmented

### ISSUE THREAD

**Issue by imsunnykr** [ngthanhtin/Line_Segmentation#2]
The solution work fine only the sample image. It segment just the first line when passed any different images. Any Solution?

**Comment by GopiReddy590** [comment]
Even i also getting the same problem can you please help me out form this.

> The solution work fine only the sample image. It segment just the first line when passed any different images. Any Solution?

**Comment by ngthanhtin** [comment]
Hi @all, sorry for the late answer, because this is a probabilistic method or you can say it is a handcrafted method, so there will be some fine-tuning steps to get it done with your images. So I recommend you try to tune https://github.com/ngthanhtin/Line_Segmentation/blob/389b2747594ff67ca48aab76d7eb70cfde4d0c5f/LineSegmentation.py#L115 this line, maybe because of blurring that makes the segmentation wrong.

**Comment by chaitu0032-debug** [comment]
![diit_63](https://user-images.githubusercontent.com/74311556/189477739-2e712883-344f-463a-a1fa-af47aae23161.jpg)

**Comment by chaitu0032-debug** [comment]
can u try for this img

**Comment by chaitu0032-debug** [comment]
also what parameters can we fine tune

**Comment by chaitu0032-debug** [comment]
it would help a lot if we know this

**Comment by chaitu0032-debug** [comment]
And also the region repair is not happening well the lines are going upward where I am expecting them to go downward

Is there a possible fix for that

**Comment by hiSyukri** [comment]
mee too

**Comment by ngthanhtin** [comment]
Hi @chaitu0032-debug , @hiSyukri  I was able to fix that, you can check my new code:

This is the results:
![Screenshot 2023-06-16 at 1 47 06 PM](https://github.com/ngthanhtin/Line_Segmentation/assets/17596799/15930f3f-744f-409c-8822-c64ba0dcdb5c)

There are 11 lines, these are 4 first extracted lines:

![Line_0](https://github.com/ngthanhtin/Line_Segmentation/assets/17596799/a46ebfec-6a59-4b6f-84c3-b7fe7d5ea7d2)

![Line_1](https://github.com/ngthanhtin/Line_Segmentation/assets/17596799/b004f130-464f-4565-bf5a-7942f99c64c2)
![Line_2](https://github.com/ngthanhtin/Line_Segmentation/assets/17596799/79fffdad-3bed-4db3-a993-4167d7d2d684)
![Line_3](https://github.com/ngthanhtin/Line_Segmentation/assets/17596799/c4aa4b29-7ffc-4b84-a34b-1deead23974c)
